apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: my-app
  namespace: flux-system
spec:
  interval: 5m0s
  path: "./blue"
  prune: true
  sourceRef:
    kind: GitRepository
    name: my-repo
    namespace: flux-system
